name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: generate-snake-game-from-github-contribution-grid
    uses: Platane/snk@v3.2.0


